version: '3.8'

services:
  node1:
    build:
      context: .
    container_name: node1
    # sovrascriviamo l’ENTRYPOINT default (gossipnode) e passiamo gli argomenti
    entrypoint: ["./gossipnode"]
    command: ["A", "0.0.0.0:8001", "node2:8002,node3:8003"]
    ports:
      - "8001:8001/udp"
    networks:
      - gossip-net

  node2:
    build:
      context: .
    container_name: node2
    entrypoint: ["./gossipnode"]
    command: ["B", "0.0.0.0:8002", "node1:8001,node3:8003"]
    ports:
      - "8002:8002/udp"
    networks:
      - gossip-net

  node3:
    build:
      context: .
    container_name: node3
    entrypoint: ["./gossipnode"]
    command: ["C", "0.0.0.0:8003", "node1:8001,node2:8002"]
    ports:
      - "8003:8003/udp"
    networks:
      - gossip-net

  registry:
    build:
      context: .
    container_name: registry
    # qui usiamo il binario registrygrpc
    entrypoint: ["./registrygrpc"]
    command: ["R", "0.0.0.0:9100", "node1:8001,node2:8002,node3:8003"]
    ports:
      - "50051:50051/tcp"
    networks:
      - gossip-net

networks:
  gossip-net:
    driver: bridge
