services:
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile.registry
    image: gossip-registry
    environment:
      - REGISTRY_PORT=${REGISTRY_PORT}
    ports:
      - "${REGISTRY_PORT}:${REGISTRY_PORT}"

  node1:
    build:
      context: ./node
      dockerfile: Dockerfile.node
    image: gossip-node
    command: ["./node", "${NODE_1_ID}", "node1:8000", "registry:${REGISTRY_PORT}"]
    ports:
      - "8000:8000"
    depends_on:
      - registry
    restart: unless-stopped

  node2:
    build:
      context: ./node
      dockerfile: Dockerfile.node
    image: gossip-node
    command: ["./node", "${NODE_2_ID}", "node2:8000", "registry:${REGISTRY_PORT}"]
    ports:
      - "8001:8000"
    depends_on:
      - registry
    restart: unless-stopped


  node3:
    build:
      context: ./node
      dockerfile: Dockerfile.node
    image: gossip-node
    command: ["./node", "${NODE_3_ID}", "node3:8000", "registry:${REGISTRY_PORT}"]
    ports:
      - "8002:8000"
    depends_on:
      - registry
    restart: unless-stopped