services:
  # --- Registry ---
  registry:
    image: registry-image-sdcc
    build:
      context: ./registry
      dockerfile: Dockerfile
    container_name: registry
    environment:
      - REGISTRY_PORT=${REGISTRY_PORT}
      - REG_FANOUT=${REG_FANOUT}
    ports:
      - "${REGISTRY_PORT}:${REGISTRY_PORT}"

  # --- Node 1 ---
  node1:
    image: node-image-sdcc
    build: .
    container_name: node1
    depends_on:
      - registry
    environment:
      - SELF_ID=${NODE1_ID}
      - SELF_ADDR=${NODE1_ID}:${NODE1_PORT}
      - REGISTRY_URL=${REGISTRY_HOST}:${REGISTRY_PORT}
      - GOSSIP_INTERVAL=${GOSSIP_INTERVAL}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - SUSPECT_TIMEOUT=${SUSPECT_TIMEOUT}
      - DEAD_TIMEOUT=${DEAD_TIMEOUT}
      - SERVICES=
      - CALC_PORT=${NODE1_CALC_PORT}
      - SERVICE_TTL=${SERVICE_TTL}
      - MAX_SERVICE_DIGEST=${MAX_SERVICE_DIGEST}
      - MAX_VOTE_DIGEST=${MAX_VOTE_DIGEST}
      - MAX_CERT_DIGEST=${MAX_CERT_DIGEST}
      - FANOUT_K=${FANOUT_K}
      - QUORUM_K=${QUORUM_K}
      - CERT_TTL=${CERT_TTL}
      - VOTE_WINDOW=${VOTE_WINDOW}
      - MAX_DIGEST_PEERS=${MAX_DIGEST_PEERS}
      - CERT_PRIORITY_ROUNDS=${CERT_PRIORITY_ROUNDS}
      - VOTE_PRIORITY_ROUNDS=${VOTE_PRIORITY_ROUNDS}
      - SERVICE_REFRESH_TIMEOUT=${SERVICE_REFRESH_TIMEOUT}
    ports:
      - "${NODE1_PORT}:${NODE1_PORT}/udp"
      - "${NODE1_PORT}:${NODE1_PORT}/tcp"
      - "${NODE1_CALC_PORT}:${NODE1_CALC_PORT}"
    restart: unless-stopped

  # --- Node 2 ---
  node2:
    image: node-image-sdcc
    container_name: node2
    depends_on: [registry]
    environment:
      - SELF_ID=${NODE2_ID}
      - SELF_ADDR=${NODE2_ID}:${NODE2_PORT}
      - REGISTRY_URL=${REGISTRY_HOST}:${REGISTRY_PORT}
      - GOSSIP_INTERVAL=${GOSSIP_INTERVAL}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - SUSPECT_TIMEOUT=${SUSPECT_TIMEOUT}
      - DEAD_TIMEOUT=${DEAD_TIMEOUT}
      - SERVICES=
      - CALC_PORT=${NODE2_CALC_PORT}
      - SERVICE_TTL=${SERVICE_TTL}
      - MAX_SERVICE_DIGEST=${MAX_SERVICE_DIGEST}
      - MAX_VOTE_DIGEST=${MAX_VOTE_DIGEST}
      - MAX_CERT_DIGEST=${MAX_CERT_DIGEST}
      - FANOUT_K=${FANOUT_K}
      - QUORUM_K=${QUORUM_K}
      - CERT_TTL=${CERT_TTL}
      - VOTE_WINDOW=${VOTE_WINDOW}
      - MAX_DIGEST_PEERS=${MAX_DIGEST_PEERS}
      - CERT_PRIORITY_ROUNDS=${CERT_PRIORITY_ROUNDS}
      - VOTE_PRIORITY_ROUNDS=${VOTE_PRIORITY_ROUNDS}
      - SERVICE_REFRESH_TIMEOUT=${SERVICE_REFRESH_TIMEOUT}
    ports:
      - "${NODE2_PORT}:${NODE2_PORT}/udp"
      - "${NODE2_PORT}:${NODE2_PORT}/tcp"
      - "${NODE2_CALC_PORT}:${NODE2_CALC_PORT}"
    restart: unless-stopped

  # --- Node 3 ---
  node3:
    image: node-image-sdcc
    container_name: node3
    depends_on: [registry]
    environment:
      - SELF_ID=${NODE3_ID}
      - SELF_ADDR=${NODE3_ID}:${NODE3_PORT}
      - REGISTRY_URL=${REGISTRY_HOST}:${REGISTRY_PORT}
      - GOSSIP_INTERVAL=${GOSSIP_INTERVAL}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - SUSPECT_TIMEOUT=${SUSPECT_TIMEOUT}
      - DEAD_TIMEOUT=${DEAD_TIMEOUT}
      - SERVICES=${NODE3_SERVICES}
      - CALC_PORT=${NODE3_CALC_PORT}
      - SERVICE_TTL=${SERVICE_TTL}
      - MAX_SERVICE_DIGEST=${MAX_SERVICE_DIGEST}
      - MAX_VOTE_DIGEST=${MAX_VOTE_DIGEST}
      - MAX_CERT_DIGEST=${MAX_CERT_DIGEST}
      - FANOUT_K=${FANOUT_K}
      - QUORUM_K=${QUORUM_K}
      - CERT_TTL=${CERT_TTL}
      - VOTE_WINDOW=${VOTE_WINDOW}
      - MAX_DIGEST_PEERS=${MAX_DIGEST_PEERS}
      - CERT_PRIORITY_ROUNDS=${CERT_PRIORITY_ROUNDS}
      - VOTE_PRIORITY_ROUNDS=${VOTE_PRIORITY_ROUNDS}
      - SERVICE_REFRESH_TIMEOUT=${SERVICE_REFRESH_TIMEOUT}
    ports:
      - "${NODE3_PORT}:${NODE3_PORT}/udp"
      - "${NODE3_PORT}:${NODE3_PORT}/tcp"
      - "${NODE3_CALC_PORT}:${NODE3_CALC_PORT}"
    restart: unless-stopped

  # --- Node 4 ---
  node4:
    image: node-image-sdcc
    container_name: node4
    depends_on: [registry]
    environment:
      - SELF_ID=${NODE4_ID}
      - SELF_ADDR=${NODE4_ID}:${NODE4_PORT}
      - REGISTRY_URL=${REGISTRY_HOST}:${REGISTRY_PORT}
      - GOSSIP_INTERVAL=${GOSSIP_INTERVAL}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - SUSPECT_TIMEOUT=${SUSPECT_TIMEOUT}
      - DEAD_TIMEOUT=${DEAD_TIMEOUT}
      - SERVICES=
      - CALC_PORT=${NODE4_CALC_PORT}
      - SERVICE_TTL=${SERVICE_TTL}
      - MAX_SERVICE_DIGEST=${MAX_SERVICE_DIGEST}
      - MAX_VOTE_DIGEST=${MAX_VOTE_DIGEST}
      - MAX_CERT_DIGEST=${MAX_CERT_DIGEST}
      - FANOUT_K=${FANOUT_K}
      - QUORUM_K=${QUORUM_K}
      - CERT_TTL=${CERT_TTL}
      - VOTE_WINDOW=${VOTE_WINDOW}
      - MAX_DIGEST_PEERS=${MAX_DIGEST_PEERS}
      - CERT_PRIORITY_ROUNDS=${CERT_PRIORITY_ROUNDS}
      - VOTE_PRIORITY_ROUNDS=${VOTE_PRIORITY_ROUNDS}
      - SERVICE_REFRESH_TIMEOUT=${SERVICE_REFRESH_TIMEOUT}
    ports:
      - "${NODE4_PORT}:${NODE4_PORT}/udp"
      - "${NODE4_PORT}:${NODE4_PORT}/tcp"
      - "${NODE4_CALC_PORT}:${NODE4_CALC_PORT}"
    restart: unless-stopped

  # --- Node 5 ---
  node5:
    image: node-image-sdcc
    container_name: node5
    depends_on: [registry]
    environment:
      - SELF_ID=${NODE5_ID}
      - SELF_ADDR=${NODE5_ID}:${NODE5_PORT}
      - REGISTRY_URL=${REGISTRY_HOST}:${REGISTRY_PORT}
      - GOSSIP_INTERVAL=${GOSSIP_INTERVAL}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - SUSPECT_TIMEOUT=${SUSPECT_TIMEOUT}
      - DEAD_TIMEOUT=${DEAD_TIMEOUT}
      - SERVICES=
      - CALC_PORT=${NODE5_CALC_PORT}
      - SERVICE_TTL=${SERVICE_TTL}
      - MAX_SERVICE_DIGEST=${MAX_SERVICE_DIGEST}
      - MAX_VOTE_DIGEST=${MAX_VOTE_DIGEST}
      - MAX_CERT_DIGEST=${MAX_CERT_DIGEST}
      - FANOUT_K=${FANOUT_K}
      - QUORUM_K=${QUORUM_K}
      - CERT_TTL=${CERT_TTL}
      - VOTE_WINDOW=${VOTE_WINDOW}
      - MAX_DIGEST_PEERS=${MAX_DIGEST_PEERS}
      - CERT_PRIORITY_ROUNDS=${CERT_PRIORITY_ROUNDS}
      - VOTE_PRIORITY_ROUNDS=${VOTE_PRIORITY_ROUNDS}
      - SERVICE_REFRESH_TIMEOUT=${SERVICE_REFRESH_TIMEOUT}
    ports:
      - "${NODE5_PORT}:${NODE5_PORT}/udp"
      - "${NODE5_PORT}:${NODE5_PORT}/tcp"
      - "${NODE5_CALC_PORT}:${NODE5_CALC_PORT}"
    restart: unless-stopped

  # --- Node 6 ---
  node6:
    image: node-image-sdcc
    container_name: node6
    depends_on: [registry]
    environment:
      - SELF_ID=${NODE6_ID}
      - SELF_ADDR=${NODE6_ID}:${NODE6_PORT}
      - REGISTRY_URL=${REGISTRY_HOST}:${REGISTRY_PORT}
      - GOSSIP_INTERVAL=${GOSSIP_INTERVAL}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - SUSPECT_TIMEOUT=${SUSPECT_TIMEOUT}
      - DEAD_TIMEOUT=${DEAD_TIMEOUT}
      - SERVICES=
      - CALC_PORT=${NODE6_CALC_PORT}
      - SERVICE_TTL=${SERVICE_TTL}
      - MAX_SERVICE_DIGEST=${MAX_SERVICE_DIGEST}
      - MAX_VOTE_DIGEST=${MAX_VOTE_DIGEST}
      - MAX_CERT_DIGEST=${MAX_CERT_DIGEST}
      - FANOUT_K=${FANOUT_K}
      - QUORUM_K=${QUORUM_K}
      - CERT_TTL=${CERT_TTL}
      - VOTE_WINDOW=${VOTE_WINDOW}
      - MAX_DIGEST_PEERS=${MAX_DIGEST_PEERS}
      - CERT_PRIORITY_ROUNDS=${CERT_PRIORITY_ROUNDS}
      - VOTE_PRIORITY_ROUNDS=${VOTE_PRIORITY_ROUNDS}
      - SERVICE_REFRESH_TIMEOUT=${SERVICE_REFRESH_TIMEOUT}
    ports:
      - "${NODE6_PORT}:${NODE6_PORT}/udp"
      - "${NODE6_PORT}:${NODE6_PORT}/tcp"
      - "${NODE6_CALC_PORT}:${NODE6_CALC_PORT}"
    restart: unless-stopped

  # --- Node 7 ---
  node7:
    image: node-image-sdcc
    container_name: node7
    depends_on: [registry]
    environment:
      - SELF_ID=${NODE7_ID}
      - SELF_ADDR=${NODE7_ID}:${NODE7_PORT}
      - REGISTRY_URL=${REGISTRY_HOST}:${REGISTRY_PORT}
      - GOSSIP_INTERVAL=${GOSSIP_INTERVAL}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - SUSPECT_TIMEOUT=${SUSPECT_TIMEOUT}
      - DEAD_TIMEOUT=${DEAD_TIMEOUT}
      - SERVICES=
      - CALC_PORT=${NODE7_CALC_PORT}
      - SERVICE_TTL=${SERVICE_TTL}
      - MAX_SERVICE_DIGEST=${MAX_SERVICE_DIGEST}
      - MAX_VOTE_DIGEST=${MAX_VOTE_DIGEST}
      - MAX_CERT_DIGEST=${MAX_CERT_DIGEST}
      - FANOUT_K=${FANOUT_K}
      - QUORUM_K=${QUORUM_K}
      - CERT_TTL=${CERT_TTL}
      - VOTE_WINDOW=${VOTE_WINDOW}
      - MAX_DIGEST_PEERS=${MAX_DIGEST_PEERS}
      - CERT_PRIORITY_ROUNDS=${CERT_PRIORITY_ROUNDS}
      - VOTE_PRIORITY_ROUNDS=${VOTE_PRIORITY_ROUNDS}
      - SERVICE_REFRESH_TIMEOUT=${SERVICE_REFRESH_TIMEOUT}
    ports:
      - "${NODE7_PORT}:${NODE7_PORT}/udp"
      - "${NODE7_PORT}:${NODE7_PORT}/tcp"
      - "${NODE7_CALC_PORT}:${NODE7_CALC_PORT}"
    restart: unless-stopped

  test_services:
    image: test_services_image_sdcc
    build:
      context: test_services
    container_name: test_services
    depends_on:
      - node1
      - node2
      - node3
    restart: no

networks:
  default:
    name: ${NETWORK_NAME}