version: "3.9"
services:
  node1:
    build: .
    container_name: node1
    environment:
      - SELF_ID=node1
      - SELF_ADDR=node1:9000
      - SEEDS=node2:9001,node3:9002,node4:9003,node5:9004,node6:9005,node7:9006
      - GOSSIP_INTERVAL=700ms
      - HEARTBEAT_INTERVAL=500ms
      - SUSPECT_TIMEOUT=2500ms
      - DEAD_TIMEOUT=6000ms
      # service discovery
      - API_PORT=8080
      - SERVICES=calc
      - CALC_PORT=18080
      - SERVICE_TTL=15
      - MAX_SERVICE_DIGEST=64
    ports:
      - "9000:9000/udp"
      - "8080:8080"      # discovery API
      - "18080:18080"    # calc

  node2:
    build: .
    container_name: node2
    environment:
      - SELF_ID=node2
      - SELF_ADDR=node2:9001
      - SEEDS=node1:9000,node3:9002,node4:9003,node5:9004,node6:9005,node7:9006
      - GOSSIP_INTERVAL=700ms
      - HEARTBEAT_INTERVAL=500ms
      - SUSPECT_TIMEOUT=2500ms
      - DEAD_TIMEOUT=6000ms
      - API_PORT=8081
      - SERVICES=calc
      - CALC_PORT=18081
      - SERVICE_TTL=15
      - MAX_SERVICE_DIGEST=64
    ports:
      - "9001:9001/udp"
      - "8081:8081"
      - "18081:18081"

  node3:
    build: .
    container_name: node3
    environment:
      - SELF_ID=node3
      - SELF_ADDR=node3:9002
      - SEEDS=node1:9000,node2:9001,node4:9003,node5:9004,node6:9005,node7:9006
      - GOSSIP_INTERVAL=700ms
      - HEARTBEAT_INTERVAL=500ms
      - SUSPECT_TIMEOUT=2500ms
      - DEAD_TIMEOUT=6000ms
      - API_PORT=8082
      - SERVICES=           # nessun servizio (vuoto)
      - SERVICE_TTL=15
      - MAX_SERVICE_DIGEST=64
    ports:
      - "9002:9002/udp"
      - "8082:8082"

  node4:
    build: .
    container_name: node4
    environment:
      - SELF_ID=node4
      - SELF_ADDR=node4:9003
      - SEEDS=node1:9000,node2:9001,node3:9002,node5:9004,node6:9005,node7:9006
      - GOSSIP_INTERVAL=700ms
      - HEARTBEAT_INTERVAL=500ms
      - SUSPECT_TIMEOUT=2500ms
      - DEAD_TIMEOUT=6000ms
      - API_PORT=8083
      - SERVICES=           # nessun servizio (vuoto)
      - SERVICE_TTL=15
      - MAX_SERVICE_DIGEST=64
    ports:
      - "9003:9003/udp"
      - "8083:8083"

  node5:
    build: .
    container_name: node5
    environment:
      - SELF_ID=node5
      - SELF_ADDR=node5:9004
      - SEEDS=node1:9000,node2:9001,node3:9002,node4:9003,node6:9005,node7:9006
      - GOSSIP_INTERVAL=700ms
      - HEARTBEAT_INTERVAL=500ms
      - SUSPECT_TIMEOUT=2500ms
      - DEAD_TIMEOUT=6000ms
      - API_PORT=8084
      - SERVICES=           # nessun servizio (vuoto)
      - SERVICE_TTL=15
      - MAX_SERVICE_DIGEST=64
    ports:
      - "9004:9004/udp"
      - "8084:8084"

  node6:
    build: .
    container_name: node6
    environment:
      - SELF_ID=node6
      - SELF_ADDR=node6:9005
      - SEEDS=node1:9000,node2:9001,node3:9002,node4:9003,node5:9004,node7:9006
      - GOSSIP_INTERVAL=700ms
      - HEARTBEAT_INTERVAL=500ms
      - SUSPECT_TIMEOUT=2500ms
      - DEAD_TIMEOUT=6000ms
      - API_PORT=8085
      - SERVICES=           # nessun servizio (vuoto)
      - SERVICE_TTL=15
      - MAX_SERVICE_DIGEST=64
    ports:
      - "9005:9005/udp"
      - "8085:8085"

  node7:
    build: .
    container_name: node7
    environment:
      - SELF_ID=node7
      - SELF_ADDR=node7:9006
      - SEEDS=node1:9000,node2:9001,node3:9002,node4:9003,node5:9004,node6:9005
      - GOSSIP_INTERVAL=700ms
      - HEARTBEAT_INTERVAL=500ms
      - SUSPECT_TIMEOUT=2500ms
      - DEAD_TIMEOUT=6000ms
      - API_PORT=8086
      - SERVICES=           # nessun servizio (vuoto)
      - SERVICE_TTL=15
      - MAX_SERVICE_DIGEST=64
    ports:
      - "9006:9006/udp"
      - "8086:8086"

  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
    restart: unless-stopped

networks:
  default:
    name: gossip-net
